main: me.frixu.playertracker.PlayerTracker
name: PlayerTracker
version: "0.1.0"
author: Frixu
api-version: "1.14"
commands:
permissions:
  frixutracker.ignoreme:
    description: Players with this permission will not be tracked.
    default: false